#-------------------------------------------------------------------------------
# Project: py-tools
#-------------------------------------------------------------------------------

[project]

name = "py-tools"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

#-------------------------------------------------------------------------------
# Build System
#-------------------------------------------------------------------------------

[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"
