#-------------------------------------------------------------------------------
# Project: monorepo
#-------------------------------------------------------------------------------

[project]

name = "monorepo"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "foundation",
]

#-------------------------------------------------------------------------------
# UV
#-------------------------------------------------------------------------------

[tool.uv.workspace]

members = [
    "apps/foundation",
]

[tool.uv.sources]

foundation = { workspace = true }
