#-------------------------------------------------------------------------------
# Project: monorepo
#-------------------------------------------------------------------------------

[project]

name = "monorepo"
version = "1.0.0"
description = "Demo monorepo build system"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "package-b",
    "service-b",
]

#-------------------------------------------------------------------------------
# Workspace
#-------------------------------------------------------------------------------

[tool.uv.workspace]

members = [
    "apps/service-b", "packages/package-b",
]

[tool.uv.sources]

package-b = { workspace = true }
service-b = { workspace = true }
