#-------------------------------------------------------------------------------
# Project: foundation
#-------------------------------------------------------------------------------

[project]

name = "k8s"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "aiohttp>=3.11.11",
    "pulumi>=3.147.0,<4.0.0",
    "pulumi-command>=1.0.1",
]

#-------------------------------------------------------------------------------
# Build System
#-------------------------------------------------------------------------------

[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"
