#-------------------------------------------------------------------------------
# Project: k8s
#-------------------------------------------------------------------------------

[project]

name = "k8s"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "tools",
]

#-------------------------------------------------------------------------------
# Build System
#-------------------------------------------------------------------------------

[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"

#-------------------------------------------------------------------------------
# UV
#-------------------------------------------------------------------------------

[tool.uv.sources]

tools = { workspace = true }
