name: Build and Test PRs
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.43"

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"

      - name: Install Dependencies
        run: bun install:all

      - name: Check Code
        run: bun run check

      - name: Test Code
        run: bun run test
